### ISSUE TITLE
Mishandling of shift+non-alphanumeric keys

### ISSUE THREAD

**Issue by slowscape** [randrew/uxn32#1]
- UXN under Windows
- Shift is recognized
- Shift+[a-z] recognized
- No other combination is recognized

All apps

**Comment by neauoire** [comment]
To test, in Left or Orca:

- `shift+3 key`, expected `#` instead of `3`

**Comment by randrew** [comment]
Thanks. Fixed by 154d1eb84ac899a571fac03fe05c10d4e2c0d07c
