### ISSUE TITLE
Requesting new build with latest changes

### ISSUE THREAD

**Issue by neauoire** [randrew/uxn32#13]
Could we have a new uxn32 build?

**Comment by randrew** [comment]
Yeah, sorry. I had to unhook my PC for a few days while I worked on a project. I'll try to do it soon.

**Comment by 22bharris** [comment]
I would kindly second this request!  I am anxious to use Orca on my 32 bit Windows tablets and uxn32 seems to be the best way to do it!

**Comment by 22bharris** [comment]
Hi there - is there any update about this new build?  Please let me know - thanks!!

**Comment by neauoire** [comment]
bump

**Comment by randrew** [comment]
Sorry 😬 gimme a few days

**Comment by randrew** [comment]
ok, done

**Comment by neauoire** [comment]
Wooh! Thanks :)
