### ISSUE TITLE
Latest Essentials Pack link in README is dead

### ISSUE THREAD

**Issue by SkiHatDuckie** [randrew/uxn32#16]
The URL leads to `uxn32-essentials.zip`, but you named the file `uxn-essentials.zip` in the 2.1 release.

I'm sorry if this is nit-picky, but I just happened to come across it when downloading Uxn for the first time.

**Comment by randrew** [comment]
Oops. Thank you very much for pointing that out. That's what I get for doing it in a rush :/ Fixed now.
