### ISSUE TITLE
Link to the Windows release broken

### ISSUE THREAD

**Issue by rahji** [randrew/uxn32#3]
The [link to the Windows release](https://github.com/randrew/uxn32/releases/download/1.4/uxn32-essentials.zip) (linked from [the 100R site ](https://100r.co/site/uxn.html) and also on the [github Releases page for this project](https://github.com/randrew/uxn32/releases)) is broken.

**Comment by randrew** [comment]
Thank you for pointing this out. I misnamed the file. I've fixed it now.

I'm sorry this took me 4 days to respond to. GitHub did not create a notification for me for this issue, so I didn't notice it.
