### ISSUE TITLE
Beetbug font is twice the size it should be

### ISSUE THREAD

**Issue by hecko-yes** [randrew/uxn32#8]
![image](https://user-images.githubusercontent.com/18291848/190853546-92e1aa53-3f17-4b7c-b30e-12a0cbd0a6c7.png)

I'm running Windows 10 on a 15' laptop (Retina-esque scaling shenanigans?) and I've once set my system locale to Japanese (but it's been since set back to Polish). I'm not holding out hope that this bug can be reproduced, but I'd be fine with just the ability to resize the panels; I can resize the window just fine, but only the rightmost panel gets wider and even it refuses to show more information:

![image](https://user-images.githubusercontent.com/18291848/190853835-124c3918-8b43-4ec7-b7c4-89ecaee0970c.png)

**Comment by randrew** [comment]
Ah, interesting. Hmm. Something is wrong. Uxn32 requests a font at a specific size and only a specific size. I didn't think it was possible for Win32 to give it a font of some other size... I'm not sure what's going on. Do you have some kind of font scaling override set in Windows?

**Comment by hecko-yes** [comment]
I didn't, but it seems that setting and then unsetting the custom display scaling value (and logging out) fixes the issue! Somehow!

**Comment by hecko-yes** [comment]
...until I restart the computer, which makes it revert back to the old font sometimes? Still, not your fault, and at least now I know how to work around it.

**Comment by hecko-yes** [comment]
...come to think of it, the font that's *supposed* to show up is taller than 6 pixels anyway. The font selection in Command Prompt says it's 6 pixels wide and 8 pixels tall (with the characters being 7 pixels). Maybe that has something to do with it? Maybe not?

**Comment by randrew** [comment]
I've heard that sometimes laptop OEMs will add something to Windows that can override and mess with font and UI metrics.
