### ISSUE TITLE
Extended delete/append port

### ISSUE THREAD

**Issue by zzo38** [randrew/uxn32#9]
My own implementation called Uxn38 has extended delete/append port if the `-x` switch is specified.

For purpose of safety, probably it should not delete a file unless the value written to the delete port is exactly 1. (I have found two programs which attempt to delete a file. One is an example program which tries to delete a file by writing the address of its name to the delete port, which is not proper (deleting the file is also unnecessary in that case). Other one does write 1 to the delete port to delete a file.)

Also, I think that deleting directories is probably unnecessary. There is no way to create directories, so deleting directories probably is not useful.

**Comment by randrew** [comment]
Sorry, but I'm not sure what the issue is here. What are you proposing or asking?

**Comment by zzo38** [comment]
I wrote a message to the mailing list of uxn (through my NNTP bridge) which describes my ideas, which includes seeking and a few other things.

You should write on the mailing list, your questions/comments/complaints about this, please. This way, we can all discuss it instead of only myself discussing it.

Since the only other program (that I know of) that deletes a file writes 1 to the delete port to delete it, this does not break the compatibility.

Also, deleting directories is unnecessary, and is not useful to do within uxn (unless, somehow later they add the possibility to create new directories, in which case deleting would make sense, but currently, it isn't).

**Comment by zzo38** [comment]
It is marked as completed, but it is not completed. It should be reopened, or implemented, or specify why it would not be implemented (and if GitHub has the possibility of marking as "won't fix" then use that, but I don't know if it does have), or deferred (e.g. if more discussion is needed, which I think it probably is).

**Comment by randrew** [comment]
I wasn't able to figure out what the issue is, if there is any, even after asking for clarification. I'm marking this as completed, because otherwise this issue item will remain an open issue on this repository forever.
